image: Visual Studio 2015
environment:
  PATH: '%PATH%;C:\texlive\bin\win32'
install:
  - bash ./install-tl-win32.sh
cache:
  - 'C:\texlive\texmf-var\fonts\cache'
build_script:
  - tlmgr install collection-langjapanese
  - platex -v
